import Head from "next/head";
import { motion as m } from "framer-motion";

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { delayChildren: 0.5, staggerChildren: 0.2 },
  },
};

const item = {
  hidden: { y: "100%" },
  show: { y: "0%", transition: { duration: 0.5 } },
};

export default function Home() {
  return (
    <m.div
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      exit={{ opacity: 1 }}
      className='text-grey-900 absolute top-0 left-0 w-full h-full bg-orange-100 lg:py-48 px-16'
    >
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='my-25'>
        <div className='my-10  overflow-hidden'>
          <m.h1
            animate={{ y: 0 }}
            initial={{ y: "100%" }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className='text-8xl text-center lg:text-right'
          >
            Hello World!
          </m.h1>
        </div>

        <div className='flex justify-between p-10'>
          <m.div variants={container} initial='hidden' animate='show'>
            <div className='overflow-hidden'>
              {" "}
              <m.h2 variants={item}>Lorem</m.h2>
            </div>
            <div className='overflow-hidden'>
              <m.h2 variants={item}>Ipsum</m.h2>
            </div>
            <div className='overflow-hidden'>
              <m.h2 variants={item}>2022</m.h2>
            </div>
          </m.div>
          <m.div variants={container} initial='hidden' animate='show'>
            <div className='overflow-hidden'>
              <m.h3 variants={item}>Lorem ipsum dolor sit amet.</m.h3>
            </div>
            <div className='overflow-hidden'>
              <m.h3 variants={item}>
                Lorem ipsum dolor sit amet consectetur.
              </m.h3>
            </div>
            <div className='overflow-hidden'>
              <m.h3 variants={item}>
                Lorem ipsum dolor sit amet consectetur adipisicing.
              </m.h3>
            </div>
          </m.div>
        </div>
      </main>
    </m.div>
  );
}
